FROM node:20-alpine

USER node
RUN mkdir -p /home/node/webapp
WORKDIR /home/node/webapp

COPY --chown=node:node ./src/webapp ./

RUN npm install

# This assumes that the `start` script in `package.json` invokes `vite`.
CMD ["npm", "start", "--", "--host=0.0.0.0", "--port=3000", "--strictPort"]
